### ISSUE TITLE
Not able to create a basic Project

### ISSUE THREAD

**Issue by narayanshivansh49** [microsoft/vscode-azure-blockchain-ethereum#15]
![2019-08-14 (1)](https://user-images.githubusercontent.com/34347884/63043532-0b235380-beea-11e9-9984-0660623dc717.png)

**Comment by caleteeter** [comment]
Thanks for this feedback @narayanshivansh49 . I just had someone else ping me about the same.  Investigating this issue.  From the title I assume everything worked, and when you clicks on the a new solidity basic project you see this break.

This likely caused by an underlying package that is looking for a C++ compiler and Python.  I am testing a new release which will remove this need for these components on your machine, but in the interium you can install the windows build tools: npm install --global windows-build-tools

``` NOTE: it must be run from an elevated powershell prompt```

**Comment by narayanshivansh49** [comment]
@caleteeter still the same...
I even tried it on my colleague's laptop he also got the same error message

**Comment by caleteeter** [comment]
I did some more testing with this @narayanshivansh49 , again sorry for this trouble.  On a clean Windows 10 1903 build, with git, nodejs, npm, python and truffle installed.  I was able to simulate this exact error when creating a new basic project.

I installed the build tools: `npm install --global windows-build-tools` from elevated PowerShell and tried again, and it worked fine.  Full transparency the reason this comes up when you provision a basic project is because we install and hdwallet provider to make the transaction signing/accounts less fragile.  This wallet has a dependency back to a crypto package, which needs a compiler (hence you see VCCLCompiler in your output message. 

So something else must be different.  I am wondering if one thing.  The build tools script usually takes a long time to install and I have seen some close it early and not get everything installed correctly.  It doesn't hurt to run it again, but can you let this run a bit longer just in case, this would be helpful to understand.

Also, just wanted to confirm your versions of dependencies:
* node - 10.16.2 is current LTS
* npm - 6.9.0 is current
* git - 2.22.0 is current
* python - 2.7.16 is current
* vscode - 1.37.0 is current
* truffle - 5.0.31 is current
* ganache-cli - 6.5.1 is current

Again really sorry for this, these dependent packages have caused us some headaches we need to make lighter weight for sure.  :)

**Comment by narayanshivansh49** [comment]
@caleteeter Thank you !!!
