### ISSUE TITLE
Saving migration to chain. Error: Error: Error: Returned error: authentication needed: password or unlock

### ISSUE THREAD

**Issue by kunaltawatia** [microsoft/vscode-azure-blockchain-ethereum#16]
Initial migration is stuck at 
```
Saving migration to chain.
[Execute Error: Error: Error: Returned error: authentication needed: password or unlock
    at Object.run (/home/venkatesh/.nvm/versions/node/v10.15.0/lib/node_modules/truffle/build/webpack:/packages/truffle-migrate/index.js:92:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
Probably an ABS configuration issue. Need Assistance.
___
Versions:
```
Truffle v5.0.31 (core: 5.0.31)
Node v10.15.0
```
___
Screenshot:

![Screenshot from 2019-08-16 18-06-55](https://user-images.githubusercontent.com/39331243/63168038-a8989780-c050-11e9-9ae8-25ac4ad393ed.png)

**Comment by caleteeter** [comment]
Hi @kunaltawatia , this looks like your truffle configuration is using an account created on an Ethereum node.  It would be good to have a look at the truffle.config that you are using here.  Because this likely contains urls and possible api keys, you should strip out the PII data before posting here (urls and paths to keys on your machine).

To give some background on what usually causes this exception, if you are connected to an Ethereum node and you are using an account that you created on that node (e.g. by running personal.newAccount or using the default one we put there for the initial transaction node), that account is locked by default and will need to be unlocked before using.  In the VS Code extension by default we get the RPC endpoint with API key and inject this into your truffle.config and we also us the truffle hdwallet provider to create an unlocked account on the fly.  We can do this on our private consortiums because there no ether required for the transactions.

An example of what you should see in your truffle configuration file (`truffle.js`):
```
const HDWalletProvider = require('truffle-hdwallet-provider');
const fs = require('fs');
module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",
      port: 8545,
      network_id: "*"
    },
    <your consortium name>: {
      network_id: "*",
      gas: 0,
      gasPrice: 0,
      provider: new HDWalletProvider(fs.readFileSync('<path to your mnemonic file', 'utf-8'), "https://<rpc endpoint and api key to your ABS instance>"),
      consortium_id: 1565960237505
    }
  },
  mocha: {},
  compilers: {
    solc: {
      version: "0.5.0"
    }
  }
};
```

**Comment by kunaltawatia** [comment]
Yes, the account used for migration is actually created by user by using`web3.eth.personal.newAccount(pass)` which was later unlocked (shown in screenschot 2), but still the error persists.
___
Screens:
1.
![Screenshot from 2019-08-16 18-38-06](https://user-images.githubusercontent.com/39331243/63169659-00d19880-c055-11e9-87da-7c53fa059d5c.png)
2.
![Screenshot from 2019-08-16 18-41-30](https://user-images.githubusercontent.com/39331243/63169877-7e95a400-c055-11e9-985e-a4f49e67d98f.png)

**Comment by caleteeter** [comment]
Thanks for the additional details @kunaltawatia .  I see the issue here now.  Few changes to support this type of deployment:

Change the truffle configuration to this:

```
var Web3 = require('web3');

module.exports = {
  networks: {
    development: {
      host: "127.0.0.1",     // Localhost (default: none)
      port: 8545,            // Standard Ethereum port (default: none)
      network_id: "*",       // Any network (default: none)
    },
    azure: {
      provider: new Web3.providers.HttpProvider("https://<your RPC url with API key>"),
      network_id: "*",
      from: '<add your account address here e.g. 0xbdb06c942dda12bd0a124b91bc051c238405bda6',
      gasPrice: 0,
      gas: 4700000
    }
  },

  mocha: {
  },

  // Configure your compilers
  compilers: {
    solc: {
      version: "0.5.1",    // Fetch exact version from solc-bin (default: truffle's version)
      settings: {          // See the solidity docs for advice about optimization and evmVersion
        evmVersion: "byzantium"
      }
    }
  }
}
```

`NOTE: The settings for the compiler and evm version in the truffle config.  This is required based on the version of ethereum/quorum in Azure Blockchain Service.  Also, set the default account and gas settings in here.`

Then in your migrations script you would do this:

```
const SimpleStorage = artifacts.require('SimpleStorage');

module.exports = (deployer) => {
    deployer.deploy(SimpleStorage);
};
```

`NOTE: No need to set account, gas, etc. here as this is driven by configuration.`

**Comment by kunaltawatia** [comment]
###### Issure resolved
