### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ifuseandprint** [microsoft/vscode-azure-blockchain-ethereum#33]
- Issue Type: `Performance`
- Extension Name: `azure-blockchain`
- Extension Version: `1.2.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.43.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\atles\AzBlockchain.azure-blockchain-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by caleteeter** [comment]
Thanks for the feedback @ifuseandprint.  We will check our profiling to see if we see hot spots.  Did you experience this at a specific area when using the extension or on activate?

**Comment by caleteeter** [comment]
I have not been able to repro this @ifuseandprint .  I do some some heightened cpu depending on action taken.  For instance, when creating a new project, there will be higher CPU use because we are installing npm packages to support the hd wallet, for a short time.  I have not seen anything egregious here.

Feel free to reopen with more details if this persists.
