### ISSUE TITLE
Error while building default template

### ISSUE THREAD

**Issue by danilotg** [microsoft/vscode-azure-blockchain-ethereum#63]
1. Expected identifier, got 'LParen'

2. SPDX license identifier not provided in source file. Before publishing, consider adding a comment containing "SPDX-License-Identifier: <SPDX-License>" to each source file. Use "SPDX-License-Identifier: UNLICENSED" for non-open-source code. Please see https://spdx.org for more information.

3. Visibility for constructor is ignored. If you want the contract to be non-deployable, making it "abstract" is sufficient.

How to fix them?

**Comment by caleteeter** [comment]
@danilotg This is because your install is using a newer compiler version, likely from the Solidity extension.  I have updated our core template used when you create a new Solidity Project -> Basic Project.  This will now use the v7 compiler with updated truffle config to accomodate.  This was pushed in PR here -> https://github.com/Azure-Samples/Blockchain-Ethereum-Template/pull/19
